name: 'Terraform Deployment'

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.1.7

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - name: Azzure Login
        run: az login --service-principal -u "942d1bda-ef9f-4d2b-aa2a-2c337a9f6950" -p "wIE8Q~smqEP6-A6EnZTfsEU-8C~lRmfzxuD_.aIf" --tenant "76ef67fe-ed5c-454c-bd45-c352f740fc8f"
        
      - name: Terraform Init
        run: | 
               terraform init -backend-config="resource_group_name=${{ secrets.AZURE_RESOURCE_GROUP }}" \
                 -backend-config="storage_account_name=${{ secrets.AZURE_STORAGE_ACCOUNT }}" \
                 -backend-config="container_name=${{ secrets.AZURE_CONTAINER_NAME }}" \
                 -backend-config="key=terraform.tfstate"
        #   terraform init \
        #     -backend-config="resource_group_name=${{ secrets.AZURE_RESOURCE_GROUP }}" \
        #     -backend-config="storage_account_name=${{ secrets.AZURE_STORAGE_ACCOUNT }}" \
        #     -backend-config="container_name=${{ secrets.AZURE_CONTAINER_NAME }}" \
        #     -backend-config="key=terraform.tfstate"        

      - name: Terraform Plan
        run: terraform plan

      - name: Terraform Apply
        if: github.event_name == 'push'
        run: terraform apply -auto-approve
        
      - name: Terraform destroy
        run: terraform destroy -auto-approve
